enableGlobalCache: true
nodeLinker: node-modules
packageExtensions:
  "@carbon/charts-react@*":
    peerDependencies:
      d3: "*"
  "@commitlint/load@*":
    peerDependencies:
      typescript: "*"
  "@data-driven-forms/carbon-component-mapper@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@manageiq/ui-components@*":
    peerDependencies:
      "@popperjs/core": "*"
  "@octokit/rest@*":
    peerDependencies:
      "@octokit/core": "*"
  "@semantic-release/github@*":
    peerDependencies:
      "@octokit/core": "*"
  angular-bootstrap-switch@*:
    peerDependencies:
      "@popperjs/core": "*"
  commitizen@*:
    peerDependencies:
      typescript: "*"
  cz-conventional-changelog@*:
    peerDependencies:
      typescript: "*"
  patternfly-react@*:
    peerDependencies:
      "@octokit/core": "*"
      redux: "*"
      typescript: "*"
  react-ellipsis-with-tooltip@*:
    peerDependencies:
      "@octokit/core": "*"
      typescript: "*"
  semantic-release@*:
    peerDependencies:
      "@octokit/core": "*"
yarnPath: .yarn/releases/yarn-3.0.2.cjs
